apiVersion: batch/v1
kind: Job
metadata:
  name: topics-quickstart
  namespace: cp-quickstart
spec:
  template:
    metadata:
      name: topics-quickstart
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:4.0.0
        command: ["kafka-topics"]
        args: ["--create", "--topic", "foo", "--partitions", "1", "--replication-factor", "1", "--if-not-exists", "--zookeeper", "zookeeper:32181"]
      restartPolicy: Never
