apiVersion: batch/v1
kind: Job
metadata:
  name: foo-test-data
  namespace: cp-quickstart
spec:
  template:
    metadata:
      name: foo-test-data
    spec:
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:4.0.0
        command: ["/bin/bash"]
        args: ["-c", "seq 42 | kafka-console-producer --request-required-acks 1 --broker-list broker-0.kafka.cp-quickstart.svc.cluster.local:29092 --topic foo && echo 'Produced 42 messages.'"]
      restartPolicy: Never
