---
apiVersion: v1
kind: Service
metadata:
  name: controlcenter
  namespace: cp-quickstart
spec:
  ports:
  - port: 32181
  clusterIP: None
  selector:
    app: controlcenter
  type: "LoadBalancer"
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: controlcenter
  namespace: cp-quickstart
spec:
  serviceName: "controlcenter"
  replicas: 1
  template:
    metadata:
      labels:
        app: controlcenter
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: controlcenter
        image: confluentinc/cp-enterprise-control-center:4.0.0
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "32181"
        - name: CONTROL_CENTER_ZOOKEEPER_CONNECT
          value: "zookeeper:32181"
        - name: CONTROL_CENTER_BOOTSTRAP_SERVERS
          value: "broker-0.kafka.cp-quickstart.svc.cluster.local:29092"
        - name: CONTROL_CENTER_CONNECT_CLUSTER
          value:"rest:8082"
        ports:
        - containerPort: 9021
